//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAGA
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        public int id { get; set; }
        public string title { get; set; }
        public string artist { get; set; }
        public Nullable<int> difficulty { get; set; }
        public string tabs { get; set; }
    }
}
